# Generated by Django 6.0.5 on 2026-05-11 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('maintain_fitness', 'Maintain Fitness'), ('improve_endurance', 'Improve Endurance')], max_length=20)),
                ('target_metric', models.FloatField(help_text='Target value (weight in kg, workout hours, etc.)')),
                ('current_value', models.FloatField(default=0)),
                ('deadline', models.DateField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('behind', 'Behind'), ('completed', 'Completed')], default='on_track', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HealthAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms')),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
