# Generated by Django 6.0.5 on 2026-05-11 07:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('running', 'Running'), ('gym', 'Gym Session'), ('cycling', 'Cycling'), ('home', 'Home Workout'), ('swimming', 'Swimming'), ('yoga', 'Yoga'), ('other', 'Other')], max_length=20)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('intense', 'Intense')], max_length=10)),
                ('calories_burned', models.IntegerField(blank=True, help_text='Estimated calories burned', null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
